export {default as About} from './About'
export {default as Home} from './Home'
export {default as Courses} from './Courses'
export {default as PrivacyPolicy} from './PrivacyPolicy'
export {default as Login} from './Login'
export {default as Signup} from './Signup'
export {default as Profile} from './Profile'